export const cards = [
    {
        id: 1,
        image: "/gallery_5.jpg",
        title: "The Florida Project: Taking Action to Help Kids Like Moonee",
        date: "June 6, 2016 / ByJohn /",
        description: "A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be...",
    },
    {
        id: 2,
        image: "/schoolLife.jpg",
        title: "Professor Albert joint research on mobile money in Tanzania",
        date: "June 6, 2016 / ByJohn /",
        description: "A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be...",
    },
    {
        id: 3,
        image: "/news_1.jpg",
        title: "A Global MBA for the next generation of business leaders",
        date: "June 6, 2016 / ByJohn /",
        description: "A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be...",
    },
    {
        id: 4,
        image: "/class_1.jpg",
        title: "Professor Tom comments on voluntary recalls by snack brands",
        date: "June 6, 2016 / ByJohn /",
        description: "A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be...",
    },
    {
        id: 5,
        image: "/about.jpg",
        title: "Professor Alexa is interviewed about Twitter’s valuation",
        date: "June 6, 2016 / ByJohn /",
        description: "A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be...",
    },
    {
        id: 6,
        title: "Kingster Public Safety Survey open through Nov. 30",
        date: "June 6, 2016 / ByJohn /",
        description: "A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be...",
    },
    {
        id: 1,
        image: "/gallery_5.jpg",
        title: "The Florida Project: Taking Action to Help Kids Like Moonee",
        date: "June 6, 2016 / ByJohn /",
        description: "A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be...",
    },
    {
        id: 2,
        image: "/schoolLife.jpg",
        title: "Professor Albert joint research on mobile money in Tanzania",
        date: "June 6, 2016 / ByJohn /",
        description: "A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be...",
    },
    {
        id: 3,
        image: "/news_1.jpg",
        title: "A Global MBA for the next generation of business leaders",
        date: "June 6, 2016 / ByJohn /",
        description: "A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be...",
    },
    {
        id: 4,
        image: "/class_1.jpg",
        title: "Professor Tom comments on voluntary recalls by snack brands",
        date: "June 6, 2016 / ByJohn /",
        description: "A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be...",
    },
    {
        id: 5,
        image: "/about.jpg",
        title: "Professor Alexa is interviewed about Twitter’s valuation",
        date: "June 6, 2016 / ByJohn /",
        description: "A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be...",
    },
    {
        id: 6,
        title: "Kingster Public Safety Survey open through Nov. 30",
        date: "June 6, 2016 / ByJohn /",
        description: "A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be...",
    },
    {
        id: 1,
        image: "/gallery_5.jpg",
        title: "The Florida Project: Taking Action to Help Kids Like Moonee",
        date: "June 6, 2016 / ByJohn /",
        description: "A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be...",
    },
    {
        id: 2,
        image: "/schoolLife.jpg",
        title: "Professor Albert joint research on mobile money in Tanzania",
        date: "June 6, 2016 / ByJohn /",
        description: "A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be...",
    },
    {
        id: 3,
        image: "/news_1.jpg",
        title: "A Global MBA for the next generation of business leaders",
        date: "June 6, 2016 / ByJohn /",
        description: "A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be...",
    },
    {
        id: 4,
        image: "/class_1.jpg",
        title: "Professor Tom comments on voluntary recalls by snack brands",
        date: "June 6, 2016 / ByJohn /",
        description: "A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be...",
    },
    {
        id: 5,
        image: "/about.jpg",
        title: "Professor Alexa is interviewed about Twitter’s valuation",
        date: "June 6, 2016 / ByJohn /",
        description: "A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be...",
    },
    {
        id: 6,
        title: "Kingster Public Safety Survey open through Nov. 30",
        date: "June 6, 2016 / ByJohn /",
        description: "A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be...",
    },
] 